name: Demo
on: push

jobs:
  ruby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.160.0
        with:
          bundler-cache: true
